[[bin]]
name = "smart_home"
path = "src/main.rs"

[[bin]]
name = "socket_emulator"
path = "src/bin/socket_emulator.rs"

[[bin]]
name = "thermometer_emulator"
path = "src/bin/thermometer_emulator.rs"

[[bin]]
name = "demo"
path = "src/bin/demo.rs"

[package]
name = "smart_home"
version = "0.2.0"          
edition = "2021"           

[dependencies]
anyhow = "1.0"
rand = "0.10.0"
crossbeam = "0.8"